requirements:
  - backend/requirements.txt:
      update: all
      pin: True
  - backend/requirements.dev.txt:
      update: all
      pin: True

pr_prefix: "[Backend Dependencies Update]"
label_prs: Under%20Review%20%EF%B8%8F
