FROM python:3.6

COPY requirements.txt .

COPY . /data_labeling
WORKDIR /data_labeling

ENV PYTHONPATH /data_labeling

RUN pip install -r requirements.txt

CMD ["python3.6", "data_labeling/api/app.py"]

EXPOSE 51000
