FROM python:3.6

WORKDIR /medtagger_backend/

COPY Makefile ./Makefile
COPY alembic ./alembic
COPY example_data/example_scan ./example_data/example_scan/
COPY medtagger ./medtagger
COPY scripts ./scripts
COPY tests ./tests

COPY .flake8 ./.flake8
COPY .pylintrc ./.pylintrc
COPY .test.pylintrc ./.test.pylintrc
COPY alembic.ini ./alembic.ini
COPY logging.conf ./logging.conf
COPY mypy.ini ./mypy.ini
COPY requirements.dev.txt ./requirements.dev.txt
COPY requirements.txt ./requirements.txt

ENV PYTHONPATH /medtagger_backend

ARG CASSANDRA_DRIVER__DISABLE_CYTHON
RUN if [ "$CASSANDRA_DRIVER__DISABLE_CYTHON" = "true" ]; then export CASS_DRIVER_NO_CYTHON=1; fi
RUN pip install -r requirements.txt

EXPOSE 51001
CMD ["make", "run_websocket_production"]

