FROM python:3.6

COPY . /medtagger
WORKDIR /medtagger

ENV PYTHONPATH /medtagger

RUN pip install -r requirements.txt

ENV C_FORCE_ROOT true
CMD ["celery", "-A", "medtagger.workers", "worker", "--loglevel=info"]
