FROM python:3.6

COPY . /data_labeling
WORKDIR /data_labeling

ENV PYTHONPATH /data_labeling

RUN pip install -r requirements.txt

ENV C_FORCE_ROOT true
CMD ["celery", "-A", "data_labeling.workers", "worker", "--loglevel=info"]

