version: '3'
services:
  hbase:
    image: dajobe/hbase
    ports:
      - 8080:8080
      - 8085:8085
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16010:16010

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: data_labeling
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: DataLabelingAPI!

  data_labeling_web:
    image: frontend/data_labeling_web
    ports:
      - 80:80

  data_labeling_api:
    image: backend/data_labeling_api
    build:
      context: .
      dockerfile: Dockerfile_api

  data_labeling_worker:
    image: backend/data_labeling_worker
    build:
      context: .
      dockerfile: Dockerfile_worker

