---

- name: Copy db host key
  copy:
    src: db-key.pem
    dest: "/home/{{ ansible_user }}/"
    mode: 0600


- name: Start database migrations
  command: docker-compose up -d --no-deps --build medtagger_backend_database_migrations
  args:
    chdir: "{{ project_remote_path }}"


- name: Start reverse-proxy
  command: docker-compose up -d --no-deps --build reverse-proxy
  args:
    chdir: "{{ project_remote_path }}"

- name: Start frontend
  command: docker-compose up -d --no-deps --build medtagger_frontend
  args:
    chdir: "{{ project_remote_path }}"

- name: Start REST backend
  command: docker-compose up -d --no-deps --build medtagger_backend_rest
  args:
    chdir: "{{ project_remote_path }}"

- name: Start backend worker
  command: docker-compose up -d --no-deps --build medtagger_backend_worker
  args:
    chdir: "{{ project_remote_path }}"

- name: Start backend websocket
  command: docker-compose up -d --no-deps --build medtagger_backend_websocket
  args:
    chdir: "{{ project_remote_path }}"
