"""Add skip_count column to Scan model

Revision ID: 01dc85c25335
Revises: e1d0a4fcf63c
Create Date: 2018-07-06 07:01:26.337468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dc85c25335'
down_revision = 'e1d0a4fcf63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Scans', sa.Column('skip_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Scans', 'skip_count')
    # ### end Alembic commands ###
