"""Add comment column to Label model

Revision ID: 14898bcabb8a
Revises: 617bf951f6a2
Create Date: 2018-07-11 08:38:47.487875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14898bcabb8a'
down_revision = '617bf951f6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Labels', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Labels', 'comment')
    # ### end Alembic commands ###
